---
title: "My Interactive Map Example"
author: "Aaron Trask"
date: "12/23/2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Here is the map of all airports in the openflights database

```{r}
suppressPackageStartupMessages(library(leaflet))

# grab all the airports from openflights
airports <- read.csv("https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat", header = FALSE)

# Airport ID 	Unique OpenFlights identifier for this airport.
# Name 	Name of airport. May or may not contain the City name.
# City 	Main city served by airport. May be spelled differently from Name.
# Country 	Country or territory where airport is located.
# IATA/FAA 	3-letter FAA code, for airports located in Country "United States of America".
# 3-letter IATA code, for all other airports.
# Blank if not assigned.
# ICAO 	4-letter ICAO code.
# Blank if not assigned.
# Latitude 	Decimal degrees, usually to six significant digits. Negative is South, positive is North.
# Longitude 	Decimal degrees, usually to six significant digits. Negative is West, positive is East.
# Altitude 	In feet.
# Timezone 	Hours offset from UTC. Fractional hours are expressed as decimals, eg. India is 5.5.
# DST 	Daylight savings time. One of E (Europe), A (US/Canada), S (South America), O (Australia), Z (New Zealand), N (None) or U (Unknown). See also: Help: Time
# Tz database time zone 	Timezone in "tz" (Olson) format, eg. "America/Los_Angeles".
# 
# The data is ISO 8859-1 (Latin-1) encoded, with no special characters.
# 
# Note: Rules for daylight savings time change from year to year and from country to country. The current data is an approximation for 2009, built on a country level. Most airports in DST-less regions in countries that generally observe DST (eg. AL, HI in the USA, NT, QL in Australia, parts of Canada) are marked incorrectly.

# fix column names
names(airports) <- c("AirportID","Name","City","Country","IATA_FAA",
                     "ICAO","Latitude","Longitude","Altitude","Timezone","DST")

# print the map of airports
m <- airports %>% leaflet() %>% addTiles() %>% 
  addMarkers(~Longitude, ~Latitude, popup= ~Name, clusterOptions = markerClusterOptions())

m
```
